# This config file is meant for settings that affect your entire site
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

#theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin    : "default"

# Site Settings
locale: "en"
title: "Jolien Noels"
name: Jolien Noels
description: "personal website"

github: "JolienNoels"

# Conversion
markdown: kramdown

# Outputting
permalink: /blog/:year/:month/:day/:title

# Defaults
defaults:
# _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
