# This config file is meant for settings that affect your entire site
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

#theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin    : "default"

# Site Settings
locale: "en"
title: "Jolien Noels"
title_separator: "-"
name: Jolien Noels
description: "personal website"

github: "JolienNoels"

# Site Author
author:
  name: "Jolien Noels"
  avatar:
  bio: "Economist"
  Location: "London"
  Links:
    - label: "Twitter"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:j.noels@lse.ac.uk
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/joliennoels"

# Conversion
markdown: kramdown

# Outputting
permalink: /blog/:year/:month/:day/:title

# Defaults
defaults:
# _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
